# Generated by Django 4.1 on 2024-07-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Answers', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AssesmentAreas',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Class', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Subject', models.CharField(max_length=255)),
                ('Subject_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('School_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Sydney_Participant', models.CharField(max_length=255)),
                ('Sydney_Percentile', models.IntegerField()),
                ('Assesment_Areas_Id', models.IntegerField()),
                ('Award_Id', models.IntegerField()),
                ('Class_Id', models.IntegerField()),
                ('Corrcet_answer_percentage_per_class', models.IntegerField()),
                ('Correct_Answer', models.CharField(max_length=255)),
                ('Student_Id', models.IntegerField()),
                ('Participant', models.CharField(max_length=255)),
                ('Student_Score', models.IntegerField()),
                ('Subject_Id', models.IntegerField()),
                ('Category_Id', models.IntegerField()),
                ('Year_level_name', models.CharField(max_length=255)),
                ('Answer_Id', models.IntegerField()),
                ('Correct_Answer_Id', models.IntegerField()),
            ],
        ),
    ]
